# Generated by Django 3.2.9 on 2021-12-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridges',
            name='model_number',
        ),
    ]
