# Generated by Django 3.2.9 on 2021-11-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='review_title',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
