# Generated by Django 3.2.9 on 2021-12-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_cartridges_model_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridges',
            name='brochure',
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
