# Generated by Django 3.2.9 on 2021-12-05 17:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211205_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_description',
            field=tinymce.models.HTMLField(default='', max_length=255),
        ),
    ]
