# Generated by Django 3.2.9 on 2022-01-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_featured_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviews',
            name='order',
        ),
    ]
