# Generated by Django 3.2.9 on 2021-11-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211128_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecifications',
            options={'verbose_name_plural': 'Product Specifications'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_rating',
        ),
    ]
