# Generated by Django 3.2.9 on 2022-01-04 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productreviews_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
