# Generated by Django 3.2.9 on 2021-11-30 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211129_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cartridges',
            options={'verbose_name_plural': 'Cartridges'},
        ),
        migrations.RemoveField(
            model_name='cartridges',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default='Brother', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartridges',
            name='compatible_printer',
            field=models.ManyToManyField(related_name='cartridges', to='products.Product'),
        ),
        migrations.AddField(
            model_name='cartridges',
            name='brand_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productbrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productbrand'),
        ),
    ]
