# Generated by Django 3.2.9 on 2021-11-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211130_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_name',
            new_name='brand',
        ),
    ]
