# Generated by Django 3.2.9 on 2021-12-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_featured_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridges',
            name='cartridge_product',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
