# Generated by Django 3.2.9 on 2021-12-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brochure',
            field=models.URLField(blank=True, null=True),
        ),
    ]
