# Generated by Django 3.2.9 on 2021-12-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='friendly_brand_name',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
